server:
  port: 8999
  servlet:
    context-path: /chenjie
spring:
  datasource:
    url: jdbc:mysql://10.236.10.1:3306/kplus?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: kplus
    password: Kplus.20190306
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: localhost
    port: 6379

mybatis:
  #加载mybatis全局配置文件
  #config-location: classpath:mybatis-config.xml
  #加载mapper.xml配置文件目录
  mapper-locations: classpath:com/jys/mybatis/mapper/*.xml
  type-aliases-package: com.jys.model
