package com.jys.mapper;

import com.jys.model.ProvinceDO;
import java.util.List;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface ProvinceDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_province
     *
     * @mbggenerated
     */
    @Delete({
        "delete from t_sys_province",
        "where tid = #{tid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_province
     *
     * @mbggenerated
     */
    @Insert({
        "insert into t_sys_province (tid, country_id, ",
        "province_code, province_name, ",
        "create_date, update_date, ",
        "del_flag)",
        "values (#{tid,jdbcType=VARCHAR}, #{countryId,jdbcType=INTEGER}, ",
        "#{provinceCode,jdbcType=VARCHAR}, #{provinceName,jdbcType=VARCHAR}, ",
        "#{createDate,jdbcType=TIMESTAMP}, #{updateDate,jdbcType=TIMESTAMP}, ",
        "#{delFlag,jdbcType=VARCHAR})"
    })
    int insert(ProvinceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_province
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "tid, country_id, province_code, province_name, create_date, update_date, del_flag",
        "from t_sys_province",
        "where tid = #{tid,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="tid", property="tid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="country_id", property="countryId", jdbcType=JdbcType.INTEGER),
        @Result(column="province_code", property="provinceCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="province_name", property="provinceName", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_date", property="createDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_date", property="updateDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="del_flag", property="delFlag", jdbcType=JdbcType.VARCHAR)
    })
    ProvinceDO selectByPrimaryKey(String tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_province
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "tid, country_id, province_code, province_name, create_date, update_date, del_flag",
        "from t_sys_province"
    })
    @Results({
        @Result(column="tid", property="tid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="country_id", property="countryId", jdbcType=JdbcType.INTEGER),
        @Result(column="province_code", property="provinceCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="province_name", property="provinceName", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_date", property="createDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_date", property="updateDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="del_flag", property="delFlag", jdbcType=JdbcType.VARCHAR)
    })
    List<ProvinceDO> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_province
     *
     * @mbggenerated
     */
    @Update({
        "update t_sys_province",
        "set country_id = #{countryId,jdbcType=INTEGER},",
          "province_code = #{provinceCode,jdbcType=VARCHAR},",
          "province_name = #{provinceName,jdbcType=VARCHAR},",
          "create_date = #{createDate,jdbcType=TIMESTAMP},",
          "update_date = #{updateDate,jdbcType=TIMESTAMP},",
          "del_flag = #{delFlag,jdbcType=VARCHAR}",
        "where tid = #{tid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(ProvinceDO record);
}